Repository muncool39/msa-project, pull requests merged in 2024-12, with the labels that each got.

#14 [Feat] 회원 가입 API
  msa.gateway/build.gradle
  msa.gateway/src/main/java/com/msa/gateway/CustomPostFilter.java
  msa.gateway/src/main/java/com/msa/gateway/CustomPreFilter.java
  msa.gateway/src/main/resources/application.yml
  msa.user/build.gradle
  msa.user/src/main/java/com/msa/user/application/service/AuthService.java
  msa.user/src/main/java/com/msa/user/config/AuditorAwareImpl.java
  msa.user/src/main/java/com/msa/user/config/BCryptPasswordConfig.java
  msa.user/src/main/java/com/msa/user/config/JpaAuditConfig.java
  msa.user/src/main/java/com/msa/user/domain/model/BaseEntity.java
  msa.user/src/main/java/com/msa/user/domain/model/Role.java
  msa.user/src/main/java/com/msa/user/domain/model/User.java
  msa.user/src/main/java/com/msa/user/domain/repository/UserRepository.java
  msa.user/src/main/java/com/msa/user/exception/ErrorCode.java
  msa.user/src/main/java/com/msa/user/exception/ExceptionMessage.java
  msa.user/src/main/java/com/msa/user/exception/GlobalControllerAdvice.java
  msa.user/src/main/java/com/msa/user/exception/UserException.java
  msa.user/src/main/java/com/msa/user/presentation/controller/AuthController.java
  msa.user/src/main/java/com/msa/user/presentation/request/SignUpRequest.java
  msa.user/src/main/java/com/msa/user/presentation/response/ApiResponse.java
Labels: feature

#17 [Feat] 주문, 배송 서비스 엔티티 설계
  .idea/.gitignore
  .idea/2. 물류시스템.iml
  .idea/compiler.xml
  .idea/git_toolbox_blame.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/material_theme_project_new.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  msa.delivery/.gitignore
  msa.delivery/build.gradle
  msa.delivery/src/main/java/com/msa/delivery/domain/entity/Address.java
  msa.delivery/src/main/java/com/msa/delivery/domain/entity/BaseEntity.java
  msa.delivery/src/main/java/com/msa/delivery/domain/entity/Delivery.java
  msa.delivery/src/main/java/com/msa/delivery/domain/entity/DeliveryHistory.java
  msa.delivery/src/main/java/com/msa/delivery/domain/entity/enums/DeliveryStatus.java
  msa.delivery/src/main/java/com/msa/delivery/presentation/DeliveryController.java
  msa.delivery/src/main/resources/application.yml
  msa.order/.gitignore
  msa.order/build.gradle
  msa.order/src/main/java/com/msa/order/application/service/OrderService.java
  msa.order/src/main/java/com/msa/order/application/service/ProductClientService.java
  msa.order/src/main/java/com/msa/order/domain/entity/BaseEntity.java
  msa.order/src/main/java/com/msa/order/domain/entity/Order.java
  msa.order/src/main/java/com/msa/order/domain/entity/enums/OrderStatus.java
  msa.order/src/main/java/com/msa/order/domain/repository/OrderRepository.java
  msa.order/src/main/java/com/msa/order/infrastructure/OrderRepositoryImpl.java
  msa.order/src/main/java/com/msa/order/infrastructure/ProductClient.java
  msa.order/src/main/java/com/msa/order/presentation/OrderController.java
  msa.order/src/main/resources/application.yml
Labels: feature

#18 [Feat] 허브 서비스 도메인 모델 구성
  msa.hub/build.gradle
  msa.hub/src/main/java/com/msa/hub/config/AuditorAwareImpl.java
  msa.hub/src/main/java/com/msa/hub/config/JpaAuditConfig.java
  msa.hub/src/main/java/com/msa/hub/domain/model/BaseEntity.java
  msa.hub/src/main/java/com/msa/hub/domain/model/Hub.java
  msa.hub/src/main/java/com/msa/hub/domain/model/HubRoute.java
  msa.hub/src/main/java/com/msa/hub/presentation/controller/HubController.java
Labels: feature

#21 [Feat] 로그인 및 인증 필터
  msa.gateway/build.gradle
  msa.gateway/src/main/java/com/msa/gateway/filter/AuthenticationFilter.java
  msa.gateway/src/main/java/com/msa/gateway/filter/CustomPostFilter.java
  msa.gateway/src/main/java/com/msa/gateway/filter/CustomPreFilter.java
  msa.gateway/src/main/java/com/msa/gateway/util/JwtUtil.java
  msa.gateway/src/main/java/com/msa/gateway/util/JwtValidationType.java
  msa.gateway/src/main/resources/application.yml
  msa.user/src/main/java/com/msa/user/application/service/AuthService.java
  msa.user/src/main/java/com/msa/user/application/service/TokenUtil.java
  msa.user/src/main/java/com/msa/user/domain/repository/UserRepository.java
  msa.user/src/main/java/com/msa/user/exception/ErrorCode.java
  msa.user/src/main/java/com/msa/user/presentation/controller/AuthController.java
  msa.user/src/main/java/com/msa/user/presentation/request/SignInRequest.java
  msa.user/src/main/resources/application.yml
Labels: feature

#25 [Feat] 주문 생성 API 구현
  msa.order/build.gradle
  msa.order/src/main/java/com/msa/order/application/service/CreateOrderService.java
  msa.order/src/main/java/com/msa/order/application/service/DeliveryManager.java
  msa.order/src/main/java/com/msa/order/application/service/OrderService.java
  msa.order/src/main/java/com/msa/order/application/service/ProductClientService.java
  msa.order/src/main/java/com/msa/order/application/service/ProductManager.java
  msa.order/src/main/java/com/msa/order/application/service/dto/CreateDeliveryRequest.java
  msa.order/src/main/java/com/msa/order/application/service/dto/CreateDeliveryResponse.java
  msa.order/src/main/java/com/msa/order/application/service/dto/ProductStockRequest.java
  msa.order/src/main/java/com/msa/order/application/service/dto/ProductStockResponse.java
  msa.order/src/main/java/com/msa/order/config/AuditorAwareImpl.java
  msa.order/src/main/java/com/msa/order/config/FeignConfiguration.java
  msa.order/src/main/java/com/msa/order/config/JpaAuditConfig.java
  msa.order/src/main/java/com/msa/order/domain/entity/Address.java
  msa.order/src/main/java/com/msa/order/domain/entity/Order.java
  msa.order/src/main/java/com/msa/order/domain/entity/enums/OrderStatus.java
  msa.order/src/main/java/com/msa/order/domain/repository/OrderRepository.java
  msa.order/src/main/java/com/msa/order/exception/BusinessException/BusinessException.java
  msa.order/src/main/java/com/msa/order/exception/BusinessException/OrderException.java
  msa.order/src/main/java/com/msa/order/exception/ErrorCode.java
  msa.order/src/main/java/com/msa/order/exception/ExceptionResponse.java
  msa.order/src/main/java/com/msa/order/exception/GlobalExceptionHandler.java
  msa.order/src/main/java/com/msa/order/infrastructure/DeliveryClient.java
  msa.order/src/main/java/com/msa/order/infrastructure/DeliveryClientFallback.java
  msa.order/src/main/java/com/msa/order/infrastructure/ProductClient.java
  msa.order/src/main/java/com/msa/order/infrastructure/ProductClientFallback.java
  msa.order/src/main/java/com/msa/order/presentation/OrderController.java
  msa.order/src/main/java/com/msa/order/presentation/request/CreateOrderRequest.java
  msa.order/src/main/java/com/msa/order/presentation/response/ApiResponse.java
Labels: feature

#28 [Feat] 허브 생성 API
  msa.gateway/src/main/java/com/msa/gateway/filter/AuthenticationFilter.java
  msa.hub/build.gradle
  msa.hub/src/main/java/com/msa/hub/application/service/HubService.java
  msa.hub/src/main/java/com/msa/hub/config/AuditorAwareImpl.java
  msa.hub/src/main/java/com/msa/hub/config/AuthenticationFilter.java
  msa.hub/src/main/java/com/msa/hub/config/SecurityConfig.java
  msa.hub/src/main/java/com/msa/hub/config/dto/UserDetail.java
  msa.hub/src/main/java/com/msa/hub/domain/config/AuditorAwareImpl.java
  msa.hub/src/main/java/com/msa/hub/domain/config/JpaAuditConfig.java
  msa.hub/src/main/java/com/msa/hub/domain/model/Hub.java
  msa.hub/src/main/java/com/msa/hub/domain/repository/HubRepository.java
  msa.hub/src/main/java/com/msa/hub/exception/ErrorCode.java
  msa.hub/src/main/java/com/msa/hub/exception/ExceptionResponse.java
  msa.hub/src/main/java/com/msa/hub/exception/GlobalControllerAdvice.java
  msa.hub/src/main/java/com/msa/hub/exception/HubException.java
  msa.hub/src/main/java/com/msa/hub/presentation/controller/HubController.java
  msa.hub/src/main/java/com/msa/hub/presentation/request/HubCreateRequest.java
  msa.hub/src/main/java/com/msa/hub/presentation/response/ApiResponse.java
Labels: feature

#27 [Feat] 업체 서비스 엔티티 설계
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/misc.xml
  msa.company/build.gradle
  msa.company/src/main/java/com/msa/company/CompanyApplication.java
  msa.company/src/main/java/com/msa/company/domain/entity/Address.java
  msa.company/src/main/java/com/msa/company/domain/entity/BaseEntity.java
  msa.company/src/main/java/com/msa/company/domain/entity/Company.java
  msa.company/src/main/java/com/msa/company/domain/entity/Product.java
  msa.company/src/main/java/com/msa/company/domain/entity/enums/CompanyStatus.java
  msa.company/src/main/java/com/msa/company/domain/entity/enums/CompanyType.java
  msa.company/src/main/resources/application.yml
Labels: feature

#38 [Feat] 주문 단건조회, 수정, 취소, 삭제 API 구현
  .DS_Store
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  msa.order/.gitignore
  msa.order/build.gradle
  msa.order/src/main/java/com/msa/order/application/annotation/RoleCheck.java
  msa.order/src/main/java/com/msa/order/application/annotation/RoleCheckAspect.java
  msa.order/src/main/java/com/msa/order/application/service/CreateOrderService.java
  msa.order/src/main/java/com/msa/order/application/service/DeliveryManager.java
  msa.order/src/main/java/com/msa/order/application/service/GetOrderService.java
  msa.order/src/main/java/com/msa/order/application/service/HubManager.java
  msa.order/src/main/java/com/msa/order/application/service/OrderModificationService.java
  msa.order/src/main/java/com/msa/order/application/service/UpdateOrderService.java
  msa.order/src/main/java/com/msa/order/application/service/dto/DeliveryData.java
  msa.order/src/main/java/com/msa/order/application/service/dto/HubData.java
  msa.order/src/main/java/com/msa/order/config/AuditorAwareImpl.java
  msa.order/src/main/java/com/msa/order/config/AuthenticationFilter.java
  msa.order/src/main/java/com/msa/order/config/SecurityConfig.java
  msa.order/src/main/java/com/msa/order/config/UserDetailImpl.java
  msa.order/src/main/java/com/msa/order/domain/entity/BaseEntity.java
  msa.order/src/main/java/com/msa/order/domain/entity/Order.java
  msa.order/src/main/java/com/msa/order/domain/entity/enums/UserRole.java
  msa.order/src/main/java/com/msa/order/exception/ErrorCode.java
  msa.order/src/main/java/com/msa/order/exception/GlobalExceptionHandler.java
  msa.order/src/main/java/com/msa/order/infrastructure/DeliveryClient.java
  msa.order/src/main/java/com/msa/order/infrastructure/DeliveryClientFallback.java
  msa.order/src/main/java/com/msa/order/infrastructure/HubClient.java
  msa.order/src/main/java/com/msa/order/infrastructure/HubClientFallback.java
  msa.order/src/main/java/com/msa/order/presentation/OrderController.java
  msa.order/src/main/java/com/msa/order/presentation/request/UpdateOrderRequest.java
Labels: feature

#37 [Feat] 허브 경로 생성 API
  msa.hub/src/main/java/com/msa/hub/application/service/HubRouteCreateService.java
  msa.hub/src/main/java/com/msa/hub/domain/model/HubRoute.java
  msa.hub/src/main/java/com/msa/hub/domain/model/Waypoint.java
  msa.hub/src/main/java/com/msa/hub/domain/repository/HubRouteRepository.java
  msa.hub/src/main/java/com/msa/hub/domain/service/DistanceCalculator.java
  msa.hub/src/main/java/com/msa/hub/domain/service/WaypointSelector.java
  msa.hub/src/main/java/com/msa/hub/exception/ErrorCode.java
  msa.hub/src/main/java/com/msa/hub/presentation/controller/HubRouteController.java
  msa.hub/src/main/java/com/msa/hub/presentation/request/HubRouteCreateRequest.java
Labels: feature

#40 [Feat] 유저 단건 조회 API
  msa.gateway/src/main/resources/application.yml
  msa.user/build.gradle
  msa.user/src/main/java/com/msa/user/application/dto/UserDetailResponse.java
  msa.user/src/main/java/com/msa/user/application/service/AuthService.java
  msa.user/src/main/java/com/msa/user/application/service/UserService.java
  msa.user/src/main/java/com/msa/user/common/TokenUtil.java
  msa.user/src/main/java/com/msa/user/common/config/AuthenticationFilter.java
  msa.user/src/main/java/com/msa/user/common/config/BCryptPasswordConfig.java
  msa.user/src/main/java/com/msa/user/common/config/SecurityConfig.java
  msa.user/src/main/java/com/msa/user/common/config/dto/UserDetail.java
  msa.user/src/main/java/com/msa/user/common/exception/ErrorCode.java
  msa.user/src/main/java/com/msa/user/common/exception/ExceptionMessage.java
  msa.user/src/main/java/com/msa/user/common/exception/GlobalControllerAdvice.java
  msa.user/src/main/java/com/msa/user/common/exception/UserException.java
  msa.user/src/main/java/com/msa/user/config/AuditorAwareImpl.java
  msa.user/src/main/java/com/msa/user/domain/config/AuditorAwareImpl.java
  msa.user/src/main/java/com/msa/user/domain/config/JpaAuditConfig.java
  msa.user/src/main/java/com/msa/user/presentation/controller/UserController.java
Labels: feature

#41 [Fix] 허브 생성 시 관리자 정보도 함께 저장되도록 수정
  msa.hub/src/main/java/com/msa/hub/application/dto/Role.java
  msa.hub/src/main/java/com/msa/hub/application/dto/UserDetailResponse.java
  msa.hub/src/main/java/com/msa/hub/application/service/HubService.java
  msa.hub/src/main/java/com/msa/hub/application/service/UserService.java
  msa.hub/src/main/java/com/msa/hub/domain/model/Hub.java
  msa.hub/src/main/java/com/msa/hub/domain/model/HubRoute.java
  msa.hub/src/main/java/com/msa/hub/exception/ErrorCode.java
  msa.hub/src/main/java/com/msa/hub/infrastructure/UserClient.java
  msa.hub/src/main/java/com/msa/hub/infrastructure/config/FeignConfig.java
  msa.hub/src/main/java/com/msa/hub/presentation/request/HubCreateRequest.java
  msa.user/src/main/java/com/msa/user/presentation/controller/UserController.java
Labels: feature

#43 [Feat] 배송 생성 API 구현
  msa.delivery/.gitignore
  msa.delivery/build.gradle
  msa.delivery/src/main/java/com/msa/delivery/application/dto/DeliveryRoutesData.java
  msa.delivery/src/main/java/com/msa/delivery/application/dto/DeliveryWorkersData.java
  msa.delivery/src/main/java/com/msa/delivery/application/dto/GetDeliveryWorkersRequest.java
  msa.delivery/src/main/java/com/msa/delivery/application/service/CreateDeliveryService.java
  msa.delivery/src/main/java/com/msa/delivery/application/service/DeliveryAssigner.java
  msa.delivery/src/main/java/com/msa/delivery/application/service/DeliveryRouteManager.java
  msa.delivery/src/main/java/com/msa/delivery/config/AuditorAwareImpl.java
  msa.delivery/src/main/java/com/msa/delivery/config/AuthenticationFilter.java
  msa.delivery/src/main/java/com/msa/delivery/config/FeignConfiguration.java
  msa.delivery/src/main/java/com/msa/delivery/config/JpaAuditConfig.java
  msa.delivery/src/main/java/com/msa/delivery/config/SecurityConfig.java
  msa.delivery/src/main/java/com/msa/delivery/config/UserDetailImpl.java
  msa.delivery/src/main/java/com/msa/delivery/domain/entity/Address.java
  msa.delivery/src/main/java/com/msa/delivery/domain/entity/Delivery.java
  msa.delivery/src/main/java/com/msa/delivery/domain/entity/DeliveryRouteHistory.java
  msa.delivery/src/main/java/com/msa/delivery/domain/entity/enums/DeliveryStatus.java
  msa.delivery/src/main/java/com/msa/delivery/domain/entity/enums/UserRole.java
  msa.delivery/src/main/java/com/msa/delivery/domain/repository/DeliveryRepository.java
  msa.delivery/src/main/java/com/msa/delivery/exception/BusinessException/BusinessException.java
  msa.delivery/src/main/java/com/msa/delivery/exception/BusinessException/UnauthorizedException.java
  msa.delivery/src/main/java/com/msa/delivery/exception/ErrorCode.java
  msa.delivery/src/main/java/com/msa/delivery/exception/ExceptionResponse.java
  msa.delivery/src/main/java/com/msa/delivery/exception/GlobalExceptionHandler.java
  msa.delivery/src/main/java/com/msa/delivery/infrastructure/DeliveryAssignClientFallback.java
  msa.delivery/src/main/java/com/msa/delivery/infrastructure/DeliveryAssignerClient.java
  msa.delivery/src/main/java/com/msa/delivery/infrastructure/DeliveryRouteClient.java
  msa.delivery/src/main/java/com/msa/delivery/infrastructure/DeliveryRouteClientFallback.java
  msa.delivery/src/main/java/com/msa/delivery/presentation/DeliveryController.java
  msa.delivery/src/main/java/com/msa/delivery/presentation/request/CreateDeliveryRequest.java
  msa.delivery/src/main/java/com/msa/delivery/presentation/response/ApiResponse.java
  msa.delivery/src/main/java/com/msa/delivery/presentation/response/CreateDeliveryResponse.java
  msa.delivery/src/test/java/com/msa/delivery/application/service/CreateDeliveryServiceTest.java
  msa.order/src/main/java/com/msa/order/application/service/CreateOrderService.java
  msa.order/src/main/java/com/msa/order/application/service/dto/CreateDeliveryRequest.java
  msa.order/src/main/java/com/msa/order/presentation/request/CreateOrderRequest.java
Labels: feature

#45 [Feat] 허브 경로 조회 및 검색 API
  msa.hub/build.gradle
  msa.hub/src/main/java/com/msa/hub/application/dto/HubRouteDetailResponse.java
  msa.hub/src/main/java/com/msa/hub/application/dto/HubRouteResponse.java
  msa.hub/src/main/java/com/msa/hub/application/dto/WayPointResponse.java
  msa.hub/src/main/java/com/msa/hub/application/service/HubRouteCreateService.java
  msa.hub/src/main/java/com/msa/hub/application/service/HubRouteReadService.java
  msa.hub/src/main/java/com/msa/hub/domain/config/QueryDslConfig.java
  msa.hub/src/main/java/com/msa/hub/domain/model/Hub.java
  msa.hub/src/main/java/com/msa/hub/domain/model/HubRoute.java
  msa.hub/src/main/java/com/msa/hub/domain/model/Waypoint.java
  msa.hub/src/main/java/com/msa/hub/domain/repository/HubRouteCustomRepository.java
  msa.hub/src/main/java/com/msa/hub/domain/repository/HubRouteCustomRepositoryImpl.java
  msa.hub/src/main/java/com/msa/hub/domain/repository/HubRouteRepository.java
  msa.hub/src/main/java/com/msa/hub/exception/ErrorCode.java
  msa.hub/src/main/java/com/msa/hub/presentation/controller/HubRouteController.java
  msa.hub/src/main/java/com/msa/hub/presentation/response/PageResponse.java
Labels: feature

#48 [Feat] 주문 전체조회 서비스 구현 및 조회서비스 권한별 로직 추가
  msa.order/build.gradle
  msa.order/src/main/java/com/msa/order/application/annotation/RoleCheck.java
  msa.order/src/main/java/com/msa/order/application/annotation/RoleCheckAspect.java
  msa.order/src/main/java/com/msa/order/application/client/DeliveryManager.java
  msa.order/src/main/java/com/msa/order/application/client/HubManager.java
  msa.order/src/main/java/com/msa/order/application/client/ProductManager.java
  msa.order/src/main/java/com/msa/order/application/client/UserManager.java
  msa.order/src/main/java/com/msa/order/application/client/dto/CompanyData.java
  msa.order/src/main/java/com/msa/order/application/client/dto/CreateDeliveryRequest.java
  msa.order/src/main/java/com/msa/order/application/client/dto/DeliveryData.java
  msa.order/src/main/java/com/msa/order/application/client/dto/HubData.java
  msa.order/src/main/java/com/msa/order/application/client/dto/ProductStockData.java
  msa.order/src/main/java/com/msa/order/application/client/dto/ProductStockRequest.java
  msa.order/src/main/java/com/msa/order/application/client/dto/UserData.java
  msa.order/src/main/java/com/msa/order/application/service/CreateOrderService.java
  msa.order/src/main/java/com/msa/order/application/service/GetOrderService.java
  msa.order/src/main/java/com/msa/order/application/service/HubManager.java
  msa.order/src/main/java/com/msa/order/application/service/ModifyOrderService.java
  msa.order/src/main/java/com/msa/order/application/service/ReadOrderService.java
  msa.order/src/main/java/com/msa/order/application/service/UpdateOrderService.java
  msa.order/src/main/java/com/msa/order/application/service/dto/OrderDetails.java
  msa.order/src/main/java/com/msa/order/config/QueryDslConfig.java
  msa.order/src/main/java/com/msa/order/domain/entity/Address.java
  msa.order/src/main/java/com/msa/order/domain/entity/BaseEntity.java
  msa.order/src/main/java/com/msa/order/domain/entity/Order.java
  msa.order/src/main/java/com/msa/order/domain/repository/OrderRepository.java
  msa.order/src/main/java/com/msa/order/domain/repository/OrderRepositoryCustom.java
  msa.order/src/main/java/com/msa/order/domain/repository/OrderRepositoryCustomImpl.java
  msa.order/src/main/java/com/msa/order/exception/BusinessException/FeignException.java
  msa.order/src/main/java/com/msa/order/exception/BusinessException/UnauthorizedException.java
  msa.order/src/main/java/com/msa/order/exception/ErrorCode.java
  msa.order/src/main/java/com/msa/order/infrastructure/DeliveryClient.java
  msa.order/src/main/java/com/msa/order/infrastructure/DeliveryClientFallback.java
  msa.order/src/main/java/com/msa/order/infrastructure/HubClient.java
  msa.order/src/main/java/com/msa/order/infrastructure/HubClientFallback.java
  msa.order/src/main/java/com/msa/order/infrastructure/OrderRepositoryImpl.java
  msa.order/src/main/java/com/msa/order/infrastructure/ProductClient.java
  msa.order/src/main/java/com/msa/order/infrastructure/ProductClientFallback.java
  msa.order/src/main/java/com/msa/order/infrastructure/UserClient.java
  msa.order/src/main/java/com/msa/order/infrastructure/UserClientFallback.java
  msa.order/src/main/java/com/msa/order/presentation/OrderController.java
  msa.order/src/main/java/com/msa/order/presentation/response/GetOrderResponse.java
  msa.order/src/main/java/com/msa/order/presentation/response/PageResponse.java
  msa.order/src/main/java/com/msa/order/presentation/response/ReadOrderResponse.java
  msa.order/src/main/resources/application.yml
  msa.order/src/main/resources/data.sql
Labels: feature

#49 [Feat] 유저의 소속 허브를 등록하는 API
  msa.hub/src/main/java/com/msa/hub/application/dto/UserDetailResponse.java
  msa.hub/src/main/java/com/msa/hub/application/service/HubService.java
  msa.hub/src/main/java/com/msa/hub/domain/model/Hub.java
  msa.hub/src/main/java/com/msa/hub/presentation/controller/HubController.java
  msa.user/src/main/java/com/msa/user/application/dto/UserDetailResponse.java
  msa.user/src/main/java/com/msa/user/application/service/HubService.java
  msa.user/src/main/java/com/msa/user/application/service/UserService.java
  msa.user/src/main/java/com/msa/user/common/exception/ErrorCode.java
  msa.user/src/main/java/com/msa/user/common/exception/ExceptionResponse.java
  msa.user/src/main/java/com/msa/user/common/exception/GlobalControllerAdvice.java
  msa.user/src/main/java/com/msa/user/domain/model/User.java
  msa.user/src/main/java/com/msa/user/infrastructure/HubClient.java
  msa.user/src/main/java/com/msa/user/infrastructure/config/FeignConfig.java
  msa.user/src/main/java/com/msa/user/presentation/controller/UserController.java
  msa.user/src/main/java/com/msa/user/presentation/request/SetBelongHubRequest.java
Labels: feature, fix

#50 [Feat] 업체 생성, 조회, 수정, 삭제 기능 구현
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/-1227594561/order.main.iml
  .idea/modules/-305194330/hub.main.iml
  .idea/modules/-33784605/delivery.main.iml
  .idea/modules/-739737170/company.main.iml
  .idea/modules/-870704070/user.main.iml
  msa.company/build.gradle
  msa.company/src/main/java/com/msa/company/CompanyApplication.java
  msa.company/src/main/java/com/msa/company/application/service/CompanyService.java
  msa.company/src/main/java/com/msa/company/config/AuthenticationFilter.java
  msa.company/src/main/java/com/msa/company/config/FeignConfig.java
  msa.company/src/main/java/com/msa/company/config/SecurityConfig.java
  msa.company/src/main/java/com/msa/company/config/dto/UserDetailImpl.java
  msa.company/src/main/java/com/msa/company/domain/config/AuditorAwareImpl.java
  msa.company/src/main/java/com/msa/company/domain/config/JpaAuditConfig.java
  msa.company/src/main/java/com/msa/company/domain/entity/Address.java
  msa.company/src/main/java/com/msa/company/domain/entity/BaseEntity.java
  msa.company/src/main/java/com/msa/company/domain/entity/Company.java
  msa.company/src/main/java/com/msa/company/domain/repository/CompanyRepository.java
  msa.company/src/main/java/com/msa/company/exception/CompanyException.java
  msa.company/src/main/java/com/msa/company/exception/ErrorCode.java
  msa.company/src/main/java/com/msa/company/exception/ErrorResponse.java
  msa.company/src/main/java/com/msa/company/exception/GlobalExceptionHandler.java
  msa.company/src/main/java/com/msa/company/infrastructure/HubClient.java
  msa.company/src/main/java/com/msa/company/presentation/controller/CompanyController.java
  msa.company/src/main/java/com/msa/company/presentation/request/AddressRequest.java
  msa.company/src/main/java/com/msa/company/presentation/request/CreateCompanyRequest.java
  msa.company/src/main/java/com/msa/company/presentation/request/UpdateCompanyRequest.java
  msa.company/src/main/java/com/msa/company/presentation/response/ApiResponse.java
  msa.company/src/main/java/com/msa/company/presentation/response/CompanyDetailResponse.java
  msa.company/src/main/java/com/msa/company/presentation/response/CompanyListResponse.java
Labels: feature

#64 [Feat] 유저 자신의 정보 수정 API
  msa.user/src/main/java/com/msa/user/application/service/UserService.java
  msa.user/src/main/java/com/msa/user/domain/model/User.java
  msa.user/src/main/java/com/msa/user/presentation/controller/UserController.java
  msa.user/src/main/java/com/msa/user/presentation/request/UserUpdateRequest.java
Labels: feature

#61 [Feat] 허브 단건 조회 API
  msa.hub/src/main/java/com/msa/hub/application/dto/HubDetailResponse.java
  msa.hub/src/main/java/com/msa/hub/application/service/HubService.java
  msa.hub/src/main/java/com/msa/hub/domain/model/BaseEntity.java
  msa.hub/src/main/java/com/msa/hub/domain/repository/HubRepository.java
  msa.hub/src/main/java/com/msa/hub/presentation/controller/HubController.java
Labels: feature

#63 [Feat] 상품 생성 기능 구현
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/modules.xml
  msa.company/src/main/java/com/msa/company/application/service/ProductService.java
  msa.company/src/main/java/com/msa/company/config/dto/UserDetailImpl.java
  msa.company/src/main/java/com/msa/company/domain/entity/Product.java
  msa.company/src/main/java/com/msa/company/domain/repository/ProductRepository.java
  msa.company/src/main/java/com/msa/company/presentation/controller/ProductController.java
  msa.company/src/main/java/com/msa/company/presentation/request/ProductRequest.java
  msa.company/src/main/resources/db/data.sql
Labels: feature

#74 [Feat] 유저 목록 조회 및 검색 API
  msa.user/build.gradle
  msa.user/src/main/java/com/msa/user/application/dto/UserBasicResponse.java
  msa.user/src/main/java/com/msa/user/application/service/UserService.java
  msa.user/src/main/java/com/msa/user/common/exception/ErrorCode.java
  msa.user/src/main/java/com/msa/user/domain/config/QueryDslConfig.java
  msa.user/src/main/java/com/msa/user/domain/model/BaseEntity.java
  msa.user/src/main/java/com/msa/user/domain/repository/UserCustomRepository.java
  msa.user/src/main/java/com/msa/user/domain/repository/UserCustomRepositoryImpl.java
  msa.user/src/main/java/com/msa/user/domain/repository/UserRepository.java
  msa.user/src/main/java/com/msa/user/presentation/controller/UserController.java
  msa.user/src/main/java/com/msa/user/presentation/response/PageResponse.java
Labels: feature

#77 [Feat] 상품 조회, 수정, 삭제, 재고 감소/복원 기능 구현
  .idea/compiler.xml
  .idea/misc.xml
  msa.company/src/main/java/com/msa/company/application/service/CompanyProductService.java
  msa.company/src/main/java/com/msa/company/application/service/CompanyService.java
  msa.company/src/main/java/com/msa/company/application/service/ProductService.java
  msa.company/src/main/java/com/msa/company/domain/config/AuditorAwareImpl.java
  msa.company/src/main/java/com/msa/company/domain/entity/BaseEntity.java
  msa.company/src/main/java/com/msa/company/domain/entity/Company.java
  msa.company/src/main/java/com/msa/company/domain/entity/Product.java
  msa.company/src/main/java/com/msa/company/domain/repository/ProductRepository.java
  msa.company/src/main/java/com/msa/company/exception/ErrorCode.java
  msa.company/src/main/java/com/msa/company/exception/GlobalExceptionHandler.java
  msa.company/src/main/java/com/msa/company/presentation/controller/CompanyController.java
  msa.company/src/main/java/com/msa/company/presentation/controller/CompanyProductController.java
  msa.company/src/main/java/com/msa/company/presentation/controller/ProductController.java
  msa.company/src/main/java/com/msa/company/presentation/request/CreateProductRequest.java
  msa.company/src/main/java/com/msa/company/presentation/request/StockRequest.java
  msa.company/src/main/java/com/msa/company/presentation/request/UpdateProductRequest.java
  msa.company/src/main/java/com/msa/company/presentation/response/CompanyDetailResponse.java
  msa.company/src/main/java/com/msa/company/presentation/response/ProductDetailResponse.java
  msa.company/src/main/java/com/msa/company/presentation/response/ProductListResponse.java
  msa.company/src/main/java/com/msa/company/presentation/response/StockResponse.java
  msa.company/src/main/resources/db/data.sql
Labels: feature

#83 [Feat] 현재 로그인한 유저 삭제 API
  msa.user/src/main/java/com/msa/user/application/service/UserService.java
  msa.user/src/main/java/com/msa/user/domain/model/BaseEntity.java
  msa.user/src/main/java/com/msa/user/presentation/controller/UserController.java
Labels: feature

#91 [Feat] 허브 루트 상세 수정 API
  msa.hub/src/main/java/com/msa/hub/application/service/HubRouteUpdateService.java
  msa.hub/src/main/java/com/msa/hub/common/exception/ErrorCode.java
  msa.hub/src/main/java/com/msa/hub/domain/model/HubRoute.java
  msa.hub/src/main/java/com/msa/hub/domain/model/Waypoint.java
  msa.hub/src/main/java/com/msa/hub/domain/repository/WaypointRepository.java
  msa.hub/src/main/java/com/msa/hub/presentation/controller/HubRouteController.java
  msa.hub/src/main/java/com/msa/hub/presentation/request/HubRouteUpdateRequest.java
  msa.hub/src/main/java/com/msa/hub/presentation/request/WaypointUpdateRequest.java
Labels: feature

#96 [Feat] 허브 조회에 캐싱 적용
  msa.hub/build.gradle
  msa.hub/src/main/java/com/msa/hub/application/service/HubRouteCreateService.java
  msa.hub/src/main/java/com/msa/hub/application/service/HubRouteReadService.java
  msa.hub/src/main/java/com/msa/hub/application/service/HubService.java
  msa.hub/src/main/java/com/msa/hub/common/config/CacheConfig.java
Labels: feature

#100 [Feat] 허브 삭제, 허브 경로 삭제 API
  msa.hub/src/main/java/com/msa/hub/application/service/HubRouteUpdateService.java
  msa.hub/src/main/java/com/msa/hub/application/service/HubService.java
  msa.hub/src/main/java/com/msa/hub/application/service/UserService.java
  msa.hub/src/main/java/com/msa/hub/domain/model/BaseEntity.java
  msa.hub/src/main/java/com/msa/hub/domain/model/Hub.java
  msa.hub/src/main/java/com/msa/hub/domain/model/HubRoute.java
  msa.hub/src/main/java/com/msa/hub/domain/model/Waypoint.java
  msa.hub/src/main/java/com/msa/hub/infrastructure/UserClient.java
  msa.hub/src/main/java/com/msa/hub/presentation/controller/HubController.java
  msa.hub/src/main/java/com/msa/hub/presentation/controller/HubRouteController.java
  msa.user/src/main/java/com/msa/user/application/service/UserService.java
  msa.user/src/main/java/com/msa/user/presentation/controller/UserController.java
Labels: feature

#103 [feat] 주문, 배송 DockerFile 추가
  msa.delivery/Dockerfile
  msa.order/Dockerfile
Labels: documentation

#95 [Docs] Create README.md
  README.md
Labels: documentation

#106 [Docs] 도커 파일
  msa.gateway/Dockerfile
  msa.hub/Dockerfile
  msa.server/Dockerfile
  msa.user/Dockerfile
Labels: documentation
